---
- name: Fetch List of Supported Yang Models
  gather_facts: no
  hosts: iosxr_lab
  collections:
    - community.yang
  tasks:
    - name: Fetch List of supported yang models
      community.yang.fetch:
      register: yang_list
